### Problem statement

3*3 grid \
Indexing 0-8 


Fish (+1 reward) on 4,6\
Death (-10 reward) and termination on 5 \
Finish and +10 reward on 8 \
-0.1 reward (can change later if we get no termination) for each step taken. 


Start at 0 \
4 actions: u,d,l,r  \
Each action has 0.25 prob initially.  


After action is decided, 0.5 prob that we take one step in that direction and 0.5 that we slip and take 2 steps in that  direction.

In [1]:
# Difference between forward and backward T -D learning
%autosave 5

Autosaving every 5 seconds


### Environment Creation of Given respective game

In [17]:
import random
import numpy as np

class Action:
    def __init__(self):
        self.L=0
        self.R=1
        self.U=2
        self.D=3
    def check(self):
        pass

class Environment:
    def __init__(self):
        self.action_space=4
        self.observation_space=9
        self.state=1
        self.done=False
        self.reward=[[0,0,0],[0,1,-10],[1,0,10]]
        
    def reset(self):
        self.state=0
        return self.state
        
    def sample(self):
        return np.random.choice([0,1,2,3],p=[0.25,0.25,0.25,0.25])
    
    def step(self,action):
        self.Reward=0
        Act=Action()
        if(self.state==0):
            if(action==Act.L):
                self.state=np.random.choice([1,2],p=[0.5,0.5])
                if(self.state==2):
                    self.Reward=self.reward[0][self.state] -0.1
                else:
                    self.Reward=self.reward[0][self.state] -0.2
                self.done=False
                
            elif (action==Act.R):
                self.state=np.random.choice([1,2],p=[0.5,0.5])
                if(self.state==2):
                    self.Reward=self.reward[0][self.state] -0.1
                else:
                    self.Reward=self.reward[0][self.state] -0.2
                self.done=False
                
                
            elif(action==Act.U):
                self.state=np.random.choice([3,6],p=[0.5,0.5])
                if self.state==3:
                    self.Reward=self.reward[1][0] -0.2
                else :
                    self.Reward=self.reward[2][0] -0.1
                self.done=False
                
            elif(action==Act.D):
                self.state=np.random.choice([3,6],p=[0.5,0.5])
                if self.state==3:
                    self.Reward=self.reward[1][0] -0.1
                else :
                    self.Reward=self.reward[2][0] -0.2
                self.done=False
                
        elif(self.state==1):
            if(action==Act.L):
                self.state=np.random.choice([0,2],p=[0.5,0.5])
                if(self.state==2):
                    self.Reward=self.reward[0][self.state] -0.2
                else:
                    self.Reward=self.reward[0][self.state] -0.1
                self.done=False
                
            elif (action==Act.R):
                self.state=np.random.choice([0,2],p=[0.5,0.5])
                if(self.state==2):
                    self.Reward=self.reward[0][self.state] -0.1
                else:
                    self.Reward=self.reward[0][self.state] -0.2
                self.done=False
                
                
            elif(action==Act.U):
                self.state=np.random.choice([4,7],p=[0.5,0.5])
                if self.state==4:
                    self.Reward=self.reward[1][1] -0.2
                else :
                    self.Reward=self.reward[2][1] -0.1
                self.done=False
                
            elif(action==Act.D):
                self.state=np.random.choice([4,7],p=[0.5,0.5])
                if self.state==4:
                    self.Reward=self.reward[1][1] -0.1
                else :
                    self.Reward=self.reward[2][1] -0.2
                self.done=False
                
        elif(self.state==2):
            if(action==Act.L):
                self.state=np.random.choice([1,0],p=[0.5,0.5])
                if(self.state==1):
                    self.Reward=self.reward[0][self.state] -0.1
                else:
                    self.Reward=self.reward[0][self.state] -0.2
                self.done=False
                
            elif (action==Act.R):
                self.state=np.random.choice([1,0],p=[0.5,0.5])
                if(self.state==0):
                    self.Reward=self.reward[0][self.state] -0.1
                else:
                    self.Reward=self.reward[0][self.state] -0.2
                self.done=False
                
                
            elif(action==Act.U):
                self.state=np.random.choice([5,8],p=[0.5,0.5])
                if self.state==5:
                    self.Reward=self.reward[1][2] 
                else :
                    self.Reward=self.reward[2][2] 
                self.done=True
                
            elif(action==Act.D):
                self.state=np.random.choice([5,8],p=[0.5,0.5])
                if self.state==5:
                    self.Reward=self.reward[1][2] 
                else :
                    self.Reward=self.reward[2][2] 
                self.done=True
                
        elif(self.state==3):
            if(action==Act.L):
                self.state=np.random.choice([5,4],p=[0.5,0.5])
                if(self.state==5):
                    self.Reward=self.reward[1][2] 
                    self.done=True
                else:
                    self.Reward=self.reward[1][1] -0.2
                    self.done=False
                
            elif (action==Act.R):
                self.state=np.random.choice([5,4],p=[0.5,0.5])
                if(self.state==4):
                    self.Reward=self.reward[1][1] -0.1
                    self.done=False
                else:
                    self.Reward=self.reward[1][2] 
                    self.done=True
                
                
            elif(action==Act.U):
                self.state=np.random.choice([0,6],p=[0.5,0.5])
                if self.state==6:
                    self.Reward=self.reward[2][0] -0.2
                else :
                    self.Reward=self.reward[0][0] -0.1
                self.done=False
                
            elif(action==Act.D):
                self.state=np.random.choice([0,6],p=[0.5,0.5])
                if self.state==6:
                    self.Reward=self.reward[2][0] -0.1
                else :
                    self.Reward=self.reward[0][0] -0.2
                self.done=False
                   
        elif(self.state==4):
            if(action==Act.L):
                self.state=np.random.choice([5,3],p=[0.5,0.5])
                if(self.state==5):
                    self.Reward=self.reward[1][2] 
                    self.done=True
                else:
                    self.Reward=self.reward[1][0] -0.2
                    self.done=False
                
            elif (action==Act.R):
                self.state=np.random.choice([5,3],p=[0.5,0.5])
                if(self.state==3):
                    self.Reward=self.reward[1][0] -0.1
                    self.done=False
                else:
                    self.Reward=self.reward[1][2] 
                    self.done=True
                
                
            elif(action==Act.U):
                self.state=np.random.choice([1,7],p=[0.5,0.5])
                if self.state==7:
                    self.Reward=self.reward[2][1] -0.2
                else :
                    self.Reward=self.reward[0][1] -0.1
                self.done=False
                
            elif(action==Act.D):
                self.state=np.random.choice([1,7],p=[0.5,0.5])
                if self.state==7:
                    self.Reward=self.reward[2][1] -0.1
                else :
                    self.Reward=self.reward[0][1] -0.2
                self.done=False
                
        elif(self.state==6):
            if(action==Act.L):
                self.state=np.random.choice([7,8],p=[0.5,0.5])
                if(self.state==8):
                    self.Reward=self.reward[2][2] 
                    self.done=True
                else:
                    self.Reward=self.reward[2][1] -0.2
                    self.done=False
                
            elif (action==Act.R):
                self.state=np.random.choice([7,8],p=[0.5,0.5])
                if(self.state==7):
                    self.Reward=self.reward[2][1] -0.1
                    self.done=False
                else:
                    self.Reward=self.reward[2][2] 
                    self.done=True
                
                
            elif(action==Act.U):
                self.state=np.random.choice([0,3],p=[0.5,0.5])
                if self.state==3:
                    self.Reward=self.reward[1][0] -0.1
                else :
                    self.Reward=self.reward[0][0] -0.2
                self.done=False
                
            elif(action==Act.D):
                self.state=np.random.choice([0,3],p=[0.5,0.5])
                if self.state==0:
                    self.Reward=self.reward[0][0] -0.1
                else :
                    self.Reward=self.reward[1][0] -0.2
                self.done=False
                
        elif(self.state==7):
            if(action==Act.L):
                self.state=np.random.choice([6,8],p=[0.5,0.5])
                if(self.state==6):
                    self.Reward=self.reward[2][0] -0.1
                    self.done=False
                else:
                    self.Reward=self.reward[2][2] 
                    self.done=True
                
            elif (action==Act.R):
                self.state=np.random.choice([6,8],p=[0.5,0.5])
                if(self.state==8):
                    self.Reward=self.reward[2][2] 
                    self.done=True
                else:
                    self.Reward=self.reward[2][0] -0.2
                    self.done=False
                
                
            elif(action==Act.U):
                self.state=np.random.choice([1,4],p=[0.5,0.5])
                if self.state==4:
                    self.Reward=self.reward[1][1] -0.1
                else :
                    self.Reward=self.reward[0][1] -0.2
                self.done=False
                
            elif(action==Act.D):
                self.state=np.random.choice([1,4],p=[0.5,0.5])
                if self.state==0:
                    self.Reward=self.reward[0][1] -0.1
                else :
                    self.Reward=self.reward[1][1] -0.2
                self.done=False
                
        return self.state,self.Reward,self.done
                       

### Human Playing game

In [9]:
env = Environment()
state = env.reset()
total_reward = 0
while True:
    action = int(input("Enter a direction: 0 (LEFT), 1 (RIGHT), 2 (UP), 3(DOWN) ->"))
    state,reward,done = env.step(action)
    total_reward  += reward;
    print("Your new state is ", state)
    print("Your current reward is", reward )
    print("Your Total reward is", total_reward )
    if(done):
        print("You entered the termination")
        break

Enter a direction: 0 (LEFT), 1 (RIGHT), 2 (UP), 3(DOWN) ->2
Your new state is  6
Your current reward is 0.9
Your Total reward is 0.9
Enter a direction: 0 (LEFT), 1 (RIGHT), 2 (UP), 3(DOWN) ->0
Your new state is  7
Your current reward is -0.2
Your Total reward is 0.7
Enter a direction: 0 (LEFT), 1 (RIGHT), 2 (UP), 3(DOWN) ->0
Your new state is  6
Your current reward is 0.9
Your Total reward is 1.6
Enter a direction: 0 (LEFT), 1 (RIGHT), 2 (UP), 3(DOWN) ->1
Your new state is  7
Your current reward is -0.1
Your Total reward is 1.5
Enter a direction: 0 (LEFT), 1 (RIGHT), 2 (UP), 3(DOWN) ->1
Your new state is  8
Your current reward is 0
Your Total reward is 1.5
You entered the termination


### Monte-Carlo Control Training 

In [29]:
class MC_agent:
    def __init__(self,enviroment,n0):
        
        self.num_episodes=30000
        
        self.max_steps_per_episode = 3000
        
        self.n0 = float(n0)
        
        self.env = enviroment
        
        self.rewards_all_episodes = []

        # N(s,a) is the number of times that action a has been selected from state s.
        self.N = np.zeros((self.env.observation_space,self.env.action_space))
        
        # Q-table for Q(s,a)
        self.Q = np.zeros((self.env.observation_space,self.env.action_space))
        
    def train(self):
        
        # Loop episodes
        for episode in range(self.num_episodes):
            
            
            #for storing each state, action pair in each step of episodes
            episode_pairs = []
            
            # get initial state for current episode
            state = self.env.reset()
            
            rewards_current_episode = 0
            
            done = False
            
            for step in range(self.max_steps_per_episode):
                
                # get optimal action, with epsilon exploration (epsilon dependent on number of visits to the state)
                # ε-greedy exploration strategy with εt = N0/(N0 + N(st))
                n_visits = sum(self.N[state, :])

                # epsilon = N0/(N0 + N(st))
                curr_epsilon = self.n0 / (self.n0 + n_visits)

                # epsilon greedy policy exploration
                if np.random.uniform(0, 1) < curr_epsilon:
                    action = self.env.sample()
                    
                else:
                    action = np.argmax(self.Q[state,:]) 
               
                # store action state pairs
                episode_pairs.append((state,action))
                
                # update visits
                # N(s,a) is the number of times that action a has been selected from state s. 
                self.N[state, action] += 1
                
                # execute action
                state,reward,done = self.env.step(action)
                
                rewards_current_episode += reward
                
                # when game ends
                if(done == True):
                    break
             
            self.rewards_all_episodes.append(rewards_current_episode)

            # Update Action value function accordingly
            for curr_state, curr_action in episode_pairs:
                
                # Alpha(learning rate)
                step = 1.0 / self.N[curr_state, curr_action]   
            
                error = rewards_current_episode - self.Q[curr_state, curr_action]
                
                self.Q[curr_state, curr_action] += step * error
                
    def showing_and_storing_q_val(self):
        
        print("\n\n********Q-table********\n")
        print(self.Q)
        #Saving Q table
        np.save('q_table_for_monti_carlo',self.Q)
        
    def accuracy(self):
        rewards_per_thousand_episodes = np.split(np.array(self.rewards_all_episodes),self.num_episodes/1000)
        count = 1000

        print("********Average reward per thousand episodes********\n")
        for r in rewards_per_thousand_episodes:
            print(count, ": ", str(sum(r/1000)))
            count += 1000
                

In [30]:
N0 = 1000
agent = MC_agent(Environment(), N0)
agent.train()
agent.showing_and_storing_q_val()
agent.accuracy()



********Q-table********

[[ 6.05277112  6.24479396 10.16044457  7.84039968]
 [ 6.4074335   6.71654378  9.16955346  7.05470563]
 [ 7.85099041  6.71993433 -0.85435897 -1.03168317]
 [-1.28939081 -2.42446643  8.87954415 10.24034258]
 [-0.79009889 -0.77927057  8.84455554 10.05736453]
 [ 0.          0.          0.          0.        ]
 [10.43243068 11.1439657   8.87250883  8.95086004]
 [11.38172881 10.85274878  7.67012474  8.42492678]
 [ 0.          0.          0.          0.        ]]
********Average reward per thousand episodes********

1000 :  3.685999999999993
2000 :  7.5199000000000105
3000 :  8.93950000000001
4000 :  9.175599999999998
5000 :  9.267100000000006
6000 :  10.033899999999985
7000 :  10.173299999999992
8000 :  10.184700000000003
9000 :  10.357899999999985
10000 :  10.30239999999998
11000 :  10.424799999999987
12000 :  10.393799999999995
13000 :  10.522999999999989
14000 :  10.534699999999994
15000 :  10.44569999999999
16000 :  10.66369999999998
17000 :  10.531799999999977


### The Code To Watch The Agent Play The Game

In [31]:
q_table=np.load('q_table_for_monti_carlo.npy')

In [32]:
import time
from IPython.display import clear_output

env= Environment()
for episode in range(9):
    Total_reward=0
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n")
    while True:        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done= env.step(action)
        if(action==0):
            print("You Took action in direction Left Ward 🠔")
            
        elif(action==1):
            print("You Took action in direction Right Ward  ➜ ")
            
        elif(action==3):
            print("You Took action in direction Upward Ward 🠕")
            
        else:
            print("You Took action in direction Down Ward 🠗 ")
            
            
        print("You are moving ",state,"->",new_state,"\n")
        
        Total_reward=Total_reward+reward
        if done:
            if new_state == 8:
                print("****You reached the goal!****")
                print("Total Reward  of EPISODE ",episode+1," is ",Total_reward,"\n")

            else:
                print("****You fell through a hole!****")
                print("Total Reward  of EPISODE ",episode+1," is ",Total_reward,"\n")

            break
            
        state = new_state
        


*****EPISODE  1 *****


You Took action in direction Down Ward 🠗 
You are moving  0 -> 6 

You Took action in direction Right Ward  ➜ 
You are moving  6 -> 8 

****You reached the goal!****
Total Reward  of EPISODE  1  is  10.9 

*****EPISODE  2 *****


You Took action in direction Down Ward 🠗 
You are moving  0 -> 3 

You Took action in direction Upward Ward 🠕
You are moving  3 -> 6 

You Took action in direction Right Ward  ➜ 
You are moving  6 -> 7 

You Took action in direction Left Ward 🠔
You are moving  7 -> 6 

You Took action in direction Right Ward  ➜ 
You are moving  6 -> 8 

****You reached the goal!****
Total Reward  of EPISODE  2  is  11.5 

*****EPISODE  3 *****


You Took action in direction Down Ward 🠗 
You are moving  0 -> 6 

You Took action in direction Right Ward  ➜ 
You are moving  6 -> 7 

You Took action in direction Left Ward 🠔
You are moving  7 -> 8 

****You reached the goal!****
Total Reward  of EPISODE  3  is  10.8 

*****EPISODE  4 *****


You Took action i

### T-D( lambada) Control Training

In [47]:
class Sarsa_Agent:
    
    def __init__(self, environment, n0, mlambda):
        self.num_episodes=10000
        self.max_steps_per_episode = 1000
        self.n0 = float(n0)
        self.env = environment
        self.mlambda = mlambda
        
        # N(s) is the number of times that state s has been visited
        # N(s,a) is the number of times that action a has been selected from state s.
        self.N = np.zeros((self.env.observation_space,
                           self.env.action_space))
        
        self.Q = np.zeros((self.env.observation_space,
                           self.env.action_space))
        
        self.rewards_all_episodes = []
        

    # get optimal action, with epsilon exploration (epsilon dependent on number of visits to the state)
    # ε-greedy exploration strategy with εt = N0/(N0 + N(st)), 
    def train_get_action(self, state):

        n_visits = sum(self.N[state, :])       

        # epsilon = N0/(N0 + N(st)
        curr_epsilon = self.n0 / (self.n0 + n_visits)
        
        # epsilon greedy policy
        if np.random.uniform(0, 1) < curr_epsilon:
            action = self.env.sample()
            return action
        else:
            action = np.argmax(self.Q[state, :])
            return action


    def train(self):        
        
        # Loop episodes
        for episode in range(self.num_episodes):
            
            self.E =np.zeros((self.env.observation_space, self.env.action_space))
            
            self.current_reward=0
            # get initial state for current episode
            state = self.env.reset()
            action = self.train_get_action(state)
            action_next = action
            done=False
            # Execute until game ends
            for step in range(self.max_steps_per_episode):
                # update visits
                
                self.N[state, action] += 1
                
                # execute action
                state_next, reward,done = self.env.step(action)
                
                self.current_reward+=reward
                q_value = self.Q[state, action]
                                
                if not done:
                    # choose next action with epsilon greedy policy
                    action_next = self.train_get_action(state_next)
                    
                    next_q_value= self.Q[state_next, action_next]
                    delta = reward + next_q_value - q_value
                else:
                    delta = reward - q_value

                
                self.E[state, action] += 1
                alpha = 1.0  / (self.N[state, action])
                
                update = alpha * delta * self.E
                self.Q += update
                self.E *= self.mlambda

                # reassign s and a
                state = state_next
                action =  action_next
                
                if(done==True):
                    break
            
            self.rewards_all_episodes.append(self.current_reward) 

    def showing_and_storing_q_val(self):
        
        print("\n\n********Q-table********\n")
        print(self.Q)
        #Saving Q table
        np.save('q_table_for_TD_learning',self.Q)
        
    def accuracy(self):
        rewards_per_thousand_episodes = np.split(np.array(self.rewards_all_episodes),self.num_episodes/1000)
        count = 1000

        print("********Average reward per thousand episodes********\n")
        for r in rewards_per_thousand_episodes:
            print(count, ": ", str(sum(r/1000)))
            count += 1000
        
                

In [49]:
N0 = 1000
mlanbda=0
agent = Sarsa_Agent(Environment(), N0,mlanbda)
agent.train()
agent.showing_and_storing_q_val()
# print(agent.rewards_all_episodes)
agent.accuracy()



********Q-table********

[[ 1.28097074  1.33098898  6.22680004  4.50706475]
 [ 1.80182428  2.01026006  4.46802953  3.09025837]
 [ 2.79379203  2.11059438  0.11904762  0.81339713]
 [-4.44241854 -4.57758391  6.54363653  4.98188643]
 [-4.30485569 -4.22984822  3.87452398  4.52282215]
 [ 0.          0.          0.          0.        ]
 [ 8.08146896  8.8386799   2.93707527  3.03386537]
 [ 8.7084463   9.26930928  1.96371532  2.32199863]
 [ 0.          0.          0.          0.        ]]
********Average reward per thousand episodes********

1000 :  4.170899999999998
2000 :  7.613400000000011
3000 :  8.623200000000017
4000 :  9.262700000000018
5000 :  9.964800000000007
6000 :  9.909200000000022
7000 :  9.88610000000002
8000 :  9.869400000000027
9000 :  10.235099999999997
10000 :  10.165900000000008
